name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    
permissions:
  contents: write
  
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create GitHub release
        uses: docker://antonyurchenko/git-release:v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRE_RELEASE: true
          DRAFT_RELEASE: true
